### ISSUE TITLE
Missing refresh of list of updatable packages, when switching testing repo off or on

### ISSUE THREAD

**Issue by Olf0** [sailfishos-chum/sailfishos-chum-gui#103]
#### Observation
1. Enable testing repository in the settings.
2. Likely there are new updatable packages displayed at the updates page.
3. Switch off testing repository in the settings again.
4. The updatable packages from step 2 are still displayed at the updates page.
5. Even a "Refresh repository" in the pulley of the main page does not resolve this: Still all updatable packages from step 2 are still displayed at the updates page.
6. Only closing and restarting the SailfishOS:Chum GUI application fixes displaying wrong updates as available.

#### Additional observation
0. If there were updates available and freshly installed before step 1 above, they are still displayed as updatable packages at the updates page throughout steps 2 to 5, only step 6 stops this.
    These (already updated) packages are displayed with *"Installed version X.Y.Z"* and *"Available version X.Y.Z"* (with identical version *X.Y.Z*).

Thus there seems to be something fundamentally wrong with the refreshing logic for the updates page.

#### Potential resolution
Do automatically and fully refresh the updates page after switching on or off the testing repository in the settings.

**Comment by rinigus** [comment]
Cannot reproduce it right now, will have to wait for package updates. In general, it should refresh all the packages on switching from regular to testing (or testing to regular), so it is a bug in implementation. Hopefully, can test it soon

**Comment by Olf0** [comment]
I wish I could have been using the issue templates: I forgot to mention the version of the SailfishOS:Chum GUI application with which I observed this.
By looking at [the release dates](https://github.com/sailfishos-chum/sailfishos-chum-gui/releases) it must have been v0.4.1.

Nevertheless, this bug is present in all versions up to (and including) v0.5.5, I tested it every now and then, mostly involuntarily.

> In general, it should refresh all the packages on switching from regular to testing (or testing to regular), so it is a bug in implementation.

Maybe it does that, but just does not refresh things at the GUI.  OTOH, I can switch between pages and the stale package list remains, only closing and re-opening the SailfishOS:Chum GUI app does.  Also note that I have never tried to install one of the packages from the SailfishOS:Chum:Testing repo after I switched back to the SailfishOS:Chum repo.

**Comment by rinigus** [comment]
I cannot reproduce it still. Every time I switch between testing and regular repository, I get the data updated. 

To chek, select some package that you want to track. Let's say "Advanced Camera". Go to that package in regular repository and note version-release under "Available version". That may depend on SFOS version that you use. For me now, Advanced Camera displays as available version: 0.9.8-1.4.1.jolla . Without closing Chum GUI, if I switch to testing repo in GUI settings and go back to Advanced Camera, I will get 0.9.8-1.9.1.jolla. So, package versioning is updated as expected.

As for not updated lists in "Updates", cannot see it either. Would have to try to catch a time when the list is different in regular and testing repo.

**Comment by Olf0** [comment]
> To check, select some package that you want to track. Let's say "Advanced Camera". Go to that package in regular repository and note version-release under "Available version". That may depend on SFOS version that you use. For me now, Advanced Camera displays as available version: 0.9.8-1.4.1.jolla . Without closing Chum GUI, if I switch to testing repo in GUI settings and go back to Advanced Camera, I will get 0.9.8-1.9.1.jolla. So, package versioning is updated as expected.

That was not the original point rsp. not the test case: It only happened with a package, which was freshly updated locally (i.e., the update was installed).

Side note: Sorry, my description was not really concise after the initial message here; I think it is unambiguous in the first message.

> As for not updated lists in "Updates", cannot see it either. Would have to try to catch a time when the list is different in regular and testing repo.

Patchmanager currently is updated in the testing, but not yet in the regular repo.

Note that the "additional observation" also requires to have updatable packages in the regular repo and having installed one of these updates from the regular repo, before you switch to the testing repo, which also must offer updateable packages.

**Comment by rinigus** [comment]
I have tested with patch manager and cannot reproduce original issue:

- switched to regular repo
- installed patch manager
- closed chum gui
- opened chum gui
- no updates
- switched to testing
- 1 update - patch manager
- switched to regular repo
- 0 updates
- switched to testing
- 1 update
- switched to regular
- 0 updates
- closed gui

I wonder if something is off in your repo configs. Check whether `ssu lr` gives multiple chum repos.

**Comment by Olf0** [comment]
```
$ ssu lr | fgrep -v openrepos
Enabled repositories (global): 
 - adaptation0    ... https://store-repository.jolla.com/releases/3.2.1.20/jolla-hw/adaptation-qualcomm-f5121/armv7hl/
 - adaptation1    ... https://store-repository.jolla.com/releases/3.2.1.20/jolla-hw/adaptation-qualcomm-f5121-dhd/armv7hl/
 - aliendalvik    ... https://store-repository.jolla.com/releases/3.2.1.20/aliendalvik/f5121/
 - apps           ... https://releases.jolla.com/jolla-apps/3.2.1.20/armv7hl/
 - customer-jolla ... https://releases.jolla.com/features/3.2.1.20/customers/jolla/armv7hl/
 - hotfixes       ... https://releases.jolla.com/releases/3.2.1.20/hotfixes/armv7hl/
 - jolla          ... https://releases.jolla.com/releases/3.2.1.20/jolla/armv7hl/
 - sailfish-eas   ... https://store-repository.jolla.com/features/3.2.1.20/sailfish-eas/armv7hl/
 - xt9            ... https://store-repository.jolla.com/features/3.2.1.20/xt9/armv7hl/

Enabled repositories (user): 
 - harbour-storeman-obs              ... https://repo.sailfishos.org/obs/home:/olf:/harbour-storeman/3.2.1.20_armv7hl/
 - sailfishos-chum-testing           ... https://repo.sailfishos.org/obs/sailfishos:/chum:/testing/3.2.1.20_armv7hl/
 - store                             ... https://store-repository.jolla.com/f5121/armv7hl/?version=3.2.1.20

Disabled repositories (global, might be overridden by user config): 

Disabled repositories (user): 
 - home                 ... https://download.jollamobile.com/home:/honeybadger/latest_armv7hl/
 - mer-tools            ... 
$
```

No, just the two OBS repos for Chum and Storeman.

I will retest sometime the upcoming days or weekend, maybe on another device.

**Comment by rinigus** [comment]
yes, that looks absolutely fine.

**Comment by Olf0** [comment]
I cannot reproduce this either, now.  Maybe I did something differently, maybe something is different, or I just had a knot in my brain.  Sorry for the seemingly unnecessary fuzz.
