### ISSUE TITLE
Suggestion: Ability to launch applications

### ISSUE THREAD

**Issue by Olf0** [sailfishos-chum/sailfishos-chum-gui#105]
### Observation
Most package managers allow to launch a GUI application, e.g. Storeman, Warehouse, all F-Droid client apps etc.  IMO it makes sense to enable users to launch an application, especially because SailfishOS sometimes does not display an application icon at the launcher right after installing an app without a reboot.

### Implementation suggestion
Add a new [bottommost pulley entry at the PackagePage](https://github.com/sailfishos-chum/sailfishos-chum-gui/blob/main/qml/pages/PackagePage.qml#L55) named "**Launch**", if a package is installed and a GUI application.

**Comment by rinigus** [comment]
That will not work (trivially) for all apps, such that don't follow Jolla Store notations (harbour-app-name). But would make sense to add such functionality, even if for limited number of packages.
