### ISSUE TITLE
Please update the "Description" field of the GitHub-"About" for sailfishos-chum-gui

### ISSUE THREAD

**Issue by Olf0** [sailfishos-chum/sailfishos-chum-gui#119]
Hurray, I am almost finished with making all the descriptions, headlines and terms concise and consistent throughout the SailfishOS:Chum "ecosystem".

The only thing left to align is the "**About**" (at the upper right of [the GitHub front-page for sailfishos-chum-gui](https://github.com/sailfishos-chum/sailfishos-chum-gui)) with the [`Summary:` from the spec file](https://github.com/sailfishos-chum/sailfishos-chum-gui/blob/main/rpm/sailfishos-chum-gui.spec#L2), which is also used [at OpenRepos](https://openrepos.net/content/olf/sailfishoschum-gui-application) and elsewhere.

Thus I am kindly asking a maintainer of this repository to click on the gear icon at the upper right of [the GitHub front-page for sailfishos-chum-gui](https://github.com/sailfishos-chum/sailfishos-chum-gui) (to the right of the text "**About**") and fill the "Description" field with:

GUI application for utilising the SailfishOS:Chum community repository

**Comment by rinigus** [comment]
Done! :)
