### ISSUE TITLE
pkcon get-packages list is reduced once in a while

### ISSUE THREAD

**Issue by rinigus** [sailfishos-chum/sailfishos-chum-gui#14]
Recording it here, probably have to raise it somewhere else. Once in a while (24h period?), on my development device, I am loosing the list of packages that are not installed. As a result, we see no packages in GUI. To get list back, pkcon refresh has to be executed

SFOS 4.3; XZ2c

**Comment by piggz** [comment]
Confirmed, it confused me too!

**Comment by rinigus** [comment]
Looks like it can happen more frequently - maybe w mess up something while testing

**Comment by rinigus** [comment]
Should be better now, with SSU handling via GUI and updated package listing. Consider closing it after all is merged

**Comment by rinigus** [comment]
Closing as it is very rare. Please reopen if it starts to happen frequently
