### ISSUE TITLE
[Help] I fail to build via CI run

### ISSUE THREAD

**Issue by Olf0** [sailfishos-chum/sailfishos-chum-gui#140]
**SailfishOS VERSION**: < 4.0.1
<br />**SailfishOS:Chum GUI application VERSION**: Both, **0.5.0** and **0.5.1**
<br />

## QUESTIONS
To play with building the SailfishOS:Chum GUI app, I submitted it at the SailfishOS-OBS from SailfishOS:Chum/sailfishos-chum-gui to a freshly created subproject `sailfishos-chum-gui` of my personal SFOS-OBS repo.
<br />

### 1. Fails to build on SFOS 3.1.0 - 3.3.0
But after I accepted the self-submitted `sailfishos-chum-gui` package, it would not build on any SailfishOS release between and including 3.1.0 and 3.3.0, due to the failing build dependency on YAML-C++ (`nothing provides pkgconfig(yaml-cpp)`).  But it does build for SFOS 3.1.0 - 3.3.0 on the same build host with (apparently) the same configuration for SailfishOS:Chum and SailfishOS:Chum testing?!?

[CI runs at GitHub fail for exactly the same reason](https://github.com/sailfishos-chum/sailfishos-chum-gui/actions/runs/3980858450/jobs/6824205115#step:4:47), but also when building with the Sailfish-SDK for 3.4.0?!?

Currently I fail to comprehend, why YAML-C++ is first [defined as a hard dependency](https://github.com/sailfishos-chum/sailfishos-chum-gui/blame/main/rpm/sailfishos-chum-gui.spec#L23), and later [gets special treatment](https://github.com/sailfishos-chum/sailfishos-chum-gui/blame/main/rpm/sailfishos-chum-gui.spec#L31-L40) on SailfishOS < 4.0.1, specifically [`%define __requires_exclude ^libyaml-cpp.*$`](https://github.com/sailfishos-chum/sailfishos-chum-gui/blame/main/rpm/sailfishos-chum-gui.spec#L38). 
But apparently YAML-C++ is needed to parse the metadata for SailfishOS:Chum.  Puzzled.
<br />

### 2. Cannot find `token-gitlab.txt` and `token-github.txt`
When compiling with a CI workflow at GitHub, [it does not find `token-gitlab.txt` and `token-github.txt`](https://github.com/sailfishos-chum/sailfishos-chum-gui/actions/runs/3980858450/jobs/6824205115#step:4:45), neither in `~/rpmbuild/SOURCES/` (where `rpmbuild` looks for them) or in `~/build/rpm/`(where [`cmake` is told to look for them](https://github.com/sailfishos-chum/sailfishos-chum-gui/blame/main/rpm/sailfishos-chum-gui.spec#L65-L66), AFAIK):
```
cat: can't open '/home/nemo/rpmbuild/SOURCES/token-github.txt': No such file or directory
cat: can't open '/home/nemo/rpmbuild/SOURCES/token-gitlab.txt': No such file or directory
[…]
cat: can't open '/home/nemo/build/rpm/token-github.txt': No such file or directory
cat: can't open '/home/nemo/build/rpm/token-gitlab.txt': No such file or directory
```
<sup>Note that the user is `nemo` on SFOS < 3.4.0</sup>

But the SailfishOS-OBS ~~finds and downloads / extracts `token-gitlab.txt` and `token-github.txt` fine~~!?!  *Edit:* It does not download or extract anything, the two files are just uploaded there.

OTOH, I fail to find them in then source tree of `sailfishos-chum-gui`:
```
$ find . -name '*.txt'
./src/CMakeLists.txt
./icons/CMakeLists.txt
./CMakeLists.txt
./translations/CMakeLists.txt
$ grep -r 'token-git..b\.txt'
rpm/sailfishos-chum-gui.spec:Source1:        token-github.txt
rpm/sailfishos-chum-gui.spec:Source2:        token-gitlab.txt
```

Hence I conclude they must be generated on-the-fly somehow and somewhere.  But where if `grep` only finds them referenced in the spec file?
<br />

@piggz, @rinigus, can one of you please point out what I am failing to find / see / comprehend.  Maybe you already have an idea / suggestion how to resolve this for CI runs at GitHub.

**Comment by rinigus** [comment]
Re OBS. Looks like we have https://build.merproject.org/package/show/sailfishos:chum/yaml-cpp . 

As for the tokens, those are available in Chum repo - see closer at what is included at OBS for GUI

**Comment by rinigus** [comment]
Note that tokens cannot be uploaded to Github - they will be disabled immediately. That could be a breaker for building GUI in CI

**Comment by Olf0** [comment]
Thank you very much.
With that knowledge It was easy to rectify the failures at SFOS-OBS: Submit `yaml-cpp` and add the two token text files.

I will ponder about how to use these at GitHub.

**Comment by Olf0** [comment]
I was able to upload and check-in a GitHub access token inside a gzipped tarball.

It would be nice if such a tarball is part of a git-checkout, which is then copied inside the docker image of the Sailfish-SDK to `~/build/` for compiling and packaging.  What would be an appropriate location for it, i.e., in which directory are two token files expected, for `rpmbuild` and `cmake` to find them?  Then I would put the gzipped tarball of them in that directory and untar it inside the running Docker image of the Sailfish-SDK, [right before invoking `mb2`](https://github.com/sailfishos-chum/sailfishos-chum-gui/blob/main/.github/workflows/ci-on-pull_req.yml_build-kaput#L35-L40).

**Comment by Olf0** [comment]
I have never used the Sailfish-SDK locally, but see in the logs of CI runs at GitHub, that for some software many build dependencies are downloaded and installed before compiling.  Hence this silly question: What is a suitable measure to make  https://build.merproject.org/package/show/sailfishos:chum/yaml-cpp available for the Sailfish-SDK, so it can be used [when calling `mb2`](https://github.com/sailfishos-chum/sailfishos-chum-gui/blob/main/.github/workflows/ci-on-pull_req.yml_build-kaput#L35-L40).  The easiest and most generic solution appears to be adding the SailfishOS:Chum repo: Can I call `ssu ar <repo>` or `zypper ar <repo>` in the Docker image of the Salfish-SDK?

**Comment by Olf0** [comment]
> I was able to upload and check-in a GitHub access token inside a gzipped tarball at GitHub.

I did not like the idea of implementing such a bad workaround, which may collapse any time when GitHub improves its security scanner (… to search inside `tar.gz` archives).  Assuming, we are not the first to encounter this issue, I searched and quickly found:
https://docs.github.com/en/actions/security-guides/encrypted-secrets#creating-encrypted-secrets-for-a-repository

Hence please copy the content of [`token-github.txt` and `token-gitlab.txt`](https://build.merproject.org/package/show/sailfishos:chum/sailfishos-chum-gui) into two new "secrets" named `Token_GitHub` and `Token_GitLab` for the repository `sailfishos-chum-gui`.

Then it is trivial for me to use them [in a CI workflow](https://docs.github.com/en/actions/security-guides/encrypted-secrets#using-encrypted-secrets-in-a-workflow).

**Comment by rinigus** [comment]
Secrets added, use them as TOKEN_GITHUB and TOKEN_GITLAB. As for "where", that would be current directory in CI. May work as you show.

**Comment by Olf0** [comment]
> Secrets added, use them as TOKEN_GITHUB and TOKEN_GITLAB. As for "where", that would be current directory in CI. May work as you show.

Neither creating the two token-text files in `~` (= initial `$PWD` = `/home/{nemo,defaultuser}) or in `build` (= `/home/{nemo,defaultuser}/build) silenced the complaints that they cannot be found.  I ended up [deploying them to both, `~/rpmbuild/SOURCES/` and `~/build/rpm`](https://github.com/sailfishos-chum/sailfishos-chum-gui/pull/141/files#diff-2e7a4d60b87933881a6588310581ee8304081776d573d4ad180656f67b6410c0R39-R43) (which is the checked out [`rpm` directory](https://github.com/sailfishos-chum/sailfishos-chum-gui/tree/main/rpm)) to silence all warnings.

You may take a brief look, if you have any idea how to simplify this or if this indicates something not working as it should (at OBS etc.).  For now I believe that OBS or `tar_git` does some magic, which these CI runs lack.

So the point "CI workflow with access token text files" is ultimately done. :rocket:
Thank you for your kind support.

**Comment by rinigus** [comment]
I have been avoiding SFOS CI, tbh. So, don't know the internals nor lack any experience with it. Sorry.

**Comment by Olf0** [comment]
> I have been avoiding SFOS CI, tbh. So, don't know the internals nor lack any experience with it. Sorry.

That is fine; never mind.  It is working; and while I do hate to not fully comprehend why, it is only GH-CI / -"actions".

But the last open point is much easier to address with [some experience in using the Sailfish-SDK interactively](https://github.com/sailfishos-chum/sailfishos-chum-gui/issues/140#issuecomment-1399631612) (which I never did):

> Hence this silly question: What is a suitable measure to make https://build.merproject.org/package/show/sailfishos:chum/yaml-cpp available for the Sailfish-SDK, so it can be used [when calling mb2](https://github.com/sailfishos-chum/sailfishos-chum-gui/blob/main/.github/workflows/ci-on-pull_req.yml_build-kaput#L35-L40)?
> 
> The easiest and most generic solution appears to be adding the SailfishOS:Chum repo: Can I call ssu ar <repo> or zypper ar <repo> in the Docker image of the Sailfish-SDK?

Note that the coderus' docker images comprise a regular Ubuntu LTS installation on which the Sailfish-SDK was installed.  So everything should be as if the Sailfish-SDK was installed on a Linux-PC / -Notebook.

**Comment by Olf0** [comment]
> I guess you can follow then https://docs.sailfishos.org/Tools/Sailfish_SDK/Building_packages/#building-packages-locally and add Chum repo for targets (SFOS version + arch) that you build for. Although, it is quickly becoming rather extensive as the list of targets is long.

Plus https://docs.sailfishos.org/Tools/Platform_SDK/Building_Packages/

This looks easy ("famous last words"), just execute a `ssu ar <repo>` before calling `mb2`.  Well, I might add an `ssu ur` and maybe a `pkcon -pv repo-set-data <repo> refresh-now true` after that to be cautions.

**Comment by Olf0** [comment]
Thanks again for the pointer (I have no idea, why I missed to find this SDK-documentation when I tried), which led me to searching and finding the `mb2` tool, because the `sfdk` command is not available (at least in Coderus' Sailfish-SDK Docker-image for 3.4.0.24, which I used for my experiments, because it is the latest release requiring an externally supplied `yaml-cpp` repectively `yaml-cpp-devel`).

I researched and understood:
* The Sailfish-SDK introduces a(nother) level of containerisation ("virtualisation"): To alter things "inside" the Sailfish-SDK, one shall use the `sfdk` command (not available here), which is a frontend for the `mb2` command (used here), which in turn is a front-end for `sb2` "inside" the Sailfish-SDK.
* Hence one must use the command `mb2` for all setup and executing steps required for the Sailfish-SDK proper on [Coderus' Sailfish-SDK Docker-images](https://github.com/CODeRUS/docker-sailfishos-platform-sdk) or his [GitHub action which utilises these images](https://github.com/CODeRUS/github-sfos-build).  I ultimately found [`mb2`'s sources with its documentation in code comments](https://github.com/sailfishos/sdk-setup/blob/master/sdk-setup/src/mb2).
* Hence one must `mb2 build-shell [--maintain] [--] [<command> [<arg>...]]` to manually configure the repository configuration, but …
  * `mb2 build-shell [<command> [<arg>...]]` executes commands in the regular user's context (`{nemo|defaultuser}`), hence a `ssu ar` or `zypper ar` fails.
     <sup>Side note: `pkcon` is installed, but the `packagekitd` is not available, rendering it is useless.</sup>
  * `mb2 build-shell --maintain [<command> [<arg>...]]` always fails with `--maintain could not be executed: No such file or directory`, regardless is using a shell internal command (e.g., `echo`) or anything else, which I have checked to be installed.
    This is in stark contrast to [its "official" documentation (examples)](https://docs.sailfishos.org/Tools/Platform_SDK/Building_Packages/#maintenance-mode) and [its internal documentation](https://github.com/sailfishos/sdk-setup/blob/master/sdk-setup/src/mb2#L620-L638).
    As this was documented as the simple and core method for satisfying external dependencies, I started to look for workarounds.
* The documentation states: [Simply put RPM dependencies in the output directory and thy will by found when calling `mb2 build`](https://github.com/sailfishos/sdk-setup/blob/master/sdk-setup/src/mb2#L212-L225).  I downloaded `yaml-cpp` and `yaml-cpp-devel` there via `curl` (which works fine) and they are not used / found!
* The global option [`--search-output-dir[={verbose|quiet}]`](https://github.com/sailfishos/sdk-setup/blob/master/sdk-setup/src/mb2#L916-L919) does find RPMs in the output directory, creates a local repository and then fails to copy them into this local repo.  Creating and putting them into `./.mb2/filtered-output-dir` (where the error indicates they are searched for) yields nothing: The `./.mb2` directory seems to be erased and newly created on each run of `mb2`.
* The global option [`-o, --output-dir <dir>`](https://github.com/sailfishos/sdk-setup/blob/master/sdk-setup/src/mb2#L906-L908) implies `--search-output-dir` and yields the same: Nothing but error messages, no matter where I located the output directory (tested `./RPMS` = `~/build/RPMs` and `~/RPMS`, because thy were used in the examples).
* Using a separate, prior call `mb2 -t SailfishOS-3.4.0.24-armv7hl -o ./RPMS build-requires --refresh pull` (or without `-o` and / or `--refresh` seems to get a little further ("Directory walk done - 2 packages", yeah!), but ultimately fails to utilise them, too. :sigh:

Ultimately these experience is in line with former ones:
* CI workflows at GitHub are a bit tedious to develop, but ultimately everything works nicely and as documented.
* Jolla's build tools mostly work for "beaten paths" (i.e., regularly used ones), but are broken for much else, regardless if these features are documented as core functionality.  The (shell) code of these tools is overly complex, full of BASHims and seems to never have undergone some sort of quality assurance, regardless if I analysed `tar_git` or `mb2`; their principal author seems to be savvy, but also seems to generate a high rate of flaws in his code (I spotted a few sure ones and some likely ones), which in combination with unnecessary complexity and lacking QA results in much broken functionality.
  As I am not willing to analyse `mb2` in depth ([as I did for `tar_git`](https://github.com/sailfishos-chum/main/issues/77#issuecomment-1079780452)), I finish this excursion with the same conclusion again: Do avoid Jolla's own tool as much as one can, because they are full of flaws; if you have to use them do not deviate from the way everybody else uses them, or you will likely run into broken functionality.

Ultimate consequence of this: CI for `sailfishos-chum-gui` will be performed on the Sailfish-SDK for 4.0.1.45 and SailfishOS-latest ([currently 4.4.0.68](https://hub.docker.com/r/coderus/sailfishos-platform-sdk/tags)).  The build tests for SailfishOS 3.1.0 to 3.4.0 will be solely on the SFOS-OBS.
