### ISSUE TITLE
How to provide SailfishOS:Chum metadata, if the `Vendor:` has to be set to someting else than `chum` in order to keep the upgrade path intact, e.g., at OpenRepos.

### ISSUE THREAD

**Issue by Olf0** [sailfishos-chum/sailfishos-chum-gui#149]
How to provide SailfishOS:Chum metadata, if the `Vendor:` has to be set to someting else than `chum` in order to keep the upgrade path intact, e.g., at OpenRepos.

**Comment by rinigus** [comment]
Do you have any package as an example of this issue?

**Comment by Olf0** [comment]
[`sfos-upgrade`](https://build.merproject.org/package/show/sailfishos:chum/sfos-upgrade)

**Comment by rinigus** [comment]
You have set yourself as a vendor which made corresponding `%if` in SPEC to be false. See the result

```
Information for package sfos-upgrade:
-------------------------------------
Repository     : sailfishos-chum-testing
Name           : sfos-upgrade
Version        : 3.9.15-1.7.1.jolla
Arch           : noarch
Vendor         : olf
Installed Size : 45.0 KiB
Installed      : No
Status         : not installed
Source package : sfos-upgrade-3.9.15-1.7.1.jolla.src
Summary        : Scripts for fail-safe upgrading of SailfishOS at the command line with logging
Description    : 
    Scripts for fail-safe and semi-automated upgrading of SailfishOS at the command
    line with logging

    Usage: sfos-upgrade [<version>|--verify|--help]

    With a version number provided as parameter it sets SSU to this version and in
    release mode before upgrading.  This is the regular use case.

    Without a version number it retrieves the one set for SSU to perform slightly
    relaxed checks, but does not alter SSU's settings for upgrading.

```

**Comment by Olf0** [comment]
Thank you.  Though now I see that I have problem: Changing the vendor breaks the upgrade path at OpenRepos.

So I assume that the only option is to enable the SailfishOS:Chum metadata unconditionally, which does not look very nice.  So what, who looks at the RPM metadata on SailfishOS?  Storeman does not display it, it takes the description from OpenRepos.

Or is there any other RPM variable I can check, which indicates that the package is being built at the SFOS-OBS?  That wozuld provide an easy way out.

**Comment by rinigus** [comment]
Not that I am aware of. Addition of vendor was made to allow users to choose the source of installed package. As a side-effect, it was used by most for %if statement. On my packages, I don't use %if and consider tag info as useful in the description (if someone checks it with zypper).

**Comment by Olf0** [comment]
I have found two ways:
- [OBS documentation: OBS-specific RPM macros](https://openbuildservice.org/help/manuals/obs-user-guide/cha.obs.supported_formats.html#sec.obs.building.spec2rpm): OBS automatically sets `%_project` and `%_repository`
- [OBS documentation: Project specific macros](https://openbuildservice.org/help/manuals/obs-user-guide/cha.obs.prjconfig.html#sec.prjconfig.macros.macrosection), which can be set in the `Project` tab

I will experiment, what I can get working a my OBS-repo@SFOS-OBS.
Aim: To find something, which carries the same value for both, SailfishOS:Chum and SailfishOS:Chum:Testing.

**Comment by rinigus** [comment]
Note that this "something" can probably be added to https://build.merproject.org/project/prjconf/sailfishos:chum . Just have to know what :)

**Comment by Olf0** [comment]
Yes, exactly, but it would have to be set in both, https://build.merproject.org/project/prjconf/sailfishos:chum and https://build.merproject.org/project/prjconf/sailfishos:chum:testing

I am currently trying
```
Macros:
  # Adds %%_chum macro definition
  %_chum 1
:Macros
```
And pondering if it should be `_chum` or  `_sailfishos_chum` or anything else, ~~and if it should be set to a numeric value or a string~~.  Answer: a boolean [0|1].  Many options and for sure many suboptimal variants come to my mind.  Ideas?

OTOH, a "simple" check for the macros set by OBS should be sufficient:
`%if "%{_project}" = "sailfishos:chum" || "%{_project}" = "sailfishos:chum:testing"

**Comment by Olf0** [comment]
Oh, I just realise that I do not really comprehend this statement:
> Addition of vendor was made to allow users to choose the source of installed package.

How would I use that?  If I have the corresponding repos enabled I do have access to all packages in it and neither `pkcon` or the SailfishOS:Chum GUI app filters for the `vendor`.  Luckily!
(`zypper` is not installed by default and `rpm` only works on local packages.)

**Comment by Olf0** [comment]
@rinigus, after a lot of checks and balances (e.g., how many underscores to use: Reading `rpm --showrc` in its entirety makes the conventions obvious) I settled on my initial suggestion:

Please set in both, https://build.merproject.org/project/prjconf/sailfishos:chum and https://build.merproject.org/project/prjconf/sailfishos:chum:testing
```
Macros:
  # Adds %%_chum boolean macro and sets it to 1
  %_chum 1
:Macros
```

Thank you!

**Comment by rinigus** [comment]
I have just added them

**Comment by rinigus** [comment]
> How would one use that? If one has a repo enabled, one has access to all packages in it and neither pkcon or the SailfishOS:Chum GUI app can filter for the vendor. Luckily!

Vendor is used automatically by pkcon and zypper. For example, if you distribute your app using Chum, Jolla Store, and OpenRepos. In Jolla Store you should keep a package without any vendor specified. In Chum, we suggest to have 'chum' as vendor - configured by default (see https://build.merproject.org/project/prjconf/sailfishos:chum:testing). In OpenRepos, you could set it to something else. Then, when user installs from one of the stores, it will stay with the same store.

For example, if you have Pure Maps installed from Jolla Store. Then, when update is released in Chum but is going through review at Jolla, users preferring Jolla Store version would not get update from Chum. That way user has a control over a channel that is used to update each app.

**Comment by Olf0** [comment]
> Vendor is used automatically by pkcon and zypper.

Sure, because of `libzypp`s ["vendor stickiness"](https://en.opensuse.org/SDB:Vendor_change_update).

 > […] That way user has a control over a channel that is used to update each app.

Well, I would say that it is the principally the repo maintainer who "controls" the `vendor` setting: fully in case of the Jolla Store, and by setting a default in case of the SailfishOS:Chum repos.  At least the packager can override this for the SailfishOS:Chum repos and is in full control of the `vendor` setting at OpenRepos.

But the *users* do not understand this at all or have any "control" over it, even though I believe that most of them are happy that this is used as a mechanism for "repository separation" (without being aware of the technical mechanism), because Jolla / SailfishOS does not support the classic repository separation / stickiness mechanisms.

But ultimately I now see that this is just a matter of semantics and / or perspective.  I just wanted to be sure that I did not miss any technical aspect.  Thank you for the clarification what you meant.

**Comment by Olf0** [comment]
*Conclusion:*
Both, `%if 0%{?_chum}` (tested by looking at [`sfos-upgrade-3.9.17`](https://github.com/Olf0/sfos-upgrade/releases/tag/3.9.17)) and `%if "%{_project}" = "sailfishos:chum" || "%{_project}" = "sailfishos:chum:testing"` (tested by looking at [`sfos-upgrade-3.9.16`](https://github.com/Olf0/sfos-upgrade/releases/tag/3.9.16)) are working fine.  I will introduce the former into [my write-up in issue \#100](https://github.com/sailfishos-chum/main/issues/100).

Thank you!
