### ISSUE TITLE
[Bug?] Upgrading SFOS 4.4.0→4.5.0 at the GUI removes SaifishOS:Chum GUI app

### ISSUE THREAD

**Issue by Olf0** [sailfishos-chum/sailfishos-chum-gui#150]
**SailfishOS VERSION** (Settings → About product → Build): 4.5.0.16
<br />**HARDWARE** (Settings → About product → Manufacturer & Product name): Any officially supported (by Jolla)
<br />**SailfishOS:Chum GUI application VERSION** (\<Top pulley\> → About): 0.5.x

#### BUG DESCRIPTION

Jolla's GUI updater removes the SailfishOS:Chum GUI application when upgrading from SailfishOS 4.4.0.x to 4.5.0.x.

#### STEPS TO REPRODUCE

Upgrade SailfishOS from 4.4.0.x to 4.5.0.x with Jolla's GUI updater while having the SailfshOS:Chum GUI application installed.

#### ADDITIONAL INFORMATION

This may be a regression, I do not remember to have seen such reports when SFOS 4.4.0 was released.  For details, see next post here.

Unfortunately, reports I saw are minimalistic:
* [FSO:release-notes4.5.0.16\#116](https://forum.sailfishos.org/t/release-notes-struven-ketju-4-5-0-16/14290/116?u=olf)
* [FSO:SFOS4.5-Feedack\#106](https://forum.sailfishos.org/t/sfos-4-5-feedback-thread/14343/106?u=olf)
* [FSO:SFOS4.5-Feedack\#154](https://forum.sailfishos.org/t/sfos-4-5-feedback-thread/14343/154?u=olf)
* [FSO:SFOS4.5-Feedack\#7](https://forum.sailfishos.org/t/sfos-4-5-feedback-thread/14343/7?u=olf)
* [FSO:SFOS4.5-Feedack\#35](https://forum.sailfishos.org/t/sfos-4-5-feedback-thread/14343/35?u=olf)

**Comment by Olf0** [comment]
As far as I understand (AFAIU) the issue, the SailfishOS:Chum GUI app has to be explicitly compiled for SailfishOS 4.5.0; the binary complied for prior versions (e.g., 4.4.0) is removed ("uninstalled") due to a unmet dependency to an older version of some library and will not install due to then same reason.

Unfortunately nobody has documented the error message in the many "is removed, does not work after upgrading to SFOS 4.5.0" postings at FSO; it would have been interesting to comprehend this issue technically, maybe there is a way to avoid this specific issue in the future.

Thus, if you have experienced this, it would be helpful to document the exact error message here.  Thank you.

**Comment by tjikkun** [comment]
`libpackagekitqt5.so.0 is needed by sailfishos-chum-gui-0.5.4-1.8.1.jolla.armv7hl`

On 4.5.0 `libpackagekitqt5.so.1` is provided

**Comment by Olf0** [comment]
Thank you @tjikkun, I should be a able to fix this in my capacity as packager, I already had [this fix enqueued](https://github.com/sailfishos-chum/sailfishos-chum-gui/pull/131#issuecomment-1365522354), but not yet rolled out, unfortunately.

**Comment by Olf0** [comment]
Technically correct assessment (in contrast to the original one here): https://github.com/sailfishos-chum/sailfishos-chum-gui/pull/131#issuecomment-1426531987

**Comment by ilpianista** [comment]
@Olf0 0.5.5 is still broken for 4.5.0 or I'm missing something?

**Comment by Olf0** [comment]
> @Olf0 0.5.5 is still broken for 4.5.0 or I'm missing something?

Is it?  Then please describe what does not work in detail here or in a new bug report.

I never read more than "does not work" at FSO and it was unclear if that related to the SailfishOS:Chum GUI application or the SailfishOS:Chum GUI Installer.  Nobody opened a bug report, nobody provided any information.  It was me opening this bug report based on guessing, which I should not have done in hindsight: If nobody cares, why should I.

Actually I have the impression that everything works fine for most, otherwise somebody would have written anything specific.  Now you are just repeating this pattern.

**Comment by ilpianista** [comment]
It's strange that you don't know about this because you bumped the SDK version in 62cb64a83, but that was after you released 0.5.5. Thus, 0.5.5 still links to the packagekit version provided by 4.4.0.68, while your current git builds using 4.5.0.16. I was expecting 0.5.6 to come out soon to address this. 

I opened #153.
