### ISSUE TITLE
Installation failed on 4.5.0.18

### ISSUE THREAD

**Issue by ilpianista** [sailfishos-chum/sailfishos-chum-gui#153]
**SailfishOS VERSION** (Settings → About product → Build): 4.5.0.18
<br />**HARDWARE** (Settings → About product → Manufacturer & Product name): Xperia 10 Plus
<br />**SailfishOS:Chum GUI application VERSION** (\<Top pulley\> → About): 0.3.0-1
<br />

#### BUG DESCRIPTION

Installation fails on 4.5.0.18.

```
2023-02-17T11:26:39+01:00 [Info] PID 14744 is logging to /var/log/sailfishos-chum-gui-installer.log.txt

2023-02-17T11:26:40+01:00 [Debug] Installed, now running: sailfishos-chum-gui-installer-0.3.0-1

2023-02-17T11:26:42+01:00 [Step 1 / 2] pkcon -pv repo-set-data sailfishos-chum refresh-now true
11:26:42	PackageKit	Verbose debugging enabled (on console 0)
11:26:42	PackageKit	role now repo-set-data
Transaction:	Setting data
11:26:42	PackageKit	notify::connected
Status: 	Waiting in queue
Status: 	Waiting for authentication
Status: 	Waiting in queue
Status: 	Starting
Status: 	Querying
Status: 	Starting
Status: 	Running
Status: 	Refreshing software list
Status: 	Finished
Results:

2023-02-17T11:26:44+01:00 [Debug] sailfishos-chum-gui-installer's main script (PID: 14744) finishes

2023-02-17T11:26:45+01:00 [Step 2 / 2] pkcon -pvy install sailfishos-chum-gui
11:26:45	PackageKit	Verbose debugging enabled (on console 0)
11:26:45	PackageKit	role now resolve
Transaction:	Resolving
Status: 	Waiting in queue
Status: 	Starting
Status: 	Querying
Package not found: sailfishos-chum-gui
11:26:45	PackageKit	role now resolve
Transaction:	Resolving
Status: 	Waiting in queue
Status: 	Starting
Status: 	Querying
Package not found: sailfishos-chum-gui
Command failed: This tool could not find any available package.
```

#### STEPS TO REPRODUCE

Try to install SailfishOS:Chum GUI Installer on a device without Chum.

#### ADDITIONAL INFORMATION

I also downloaded the RPM from your 0.5.5 zip to install 0.5.5, but the RPM installation fails because it links to `libpackagekitqt5.so.0`.

**Comment by Olf0** [comment]
1. Thank you for the proper bug report.

2. > ADDITIONAL INFORMATION
   > I also downloaded the RPM from your 0.5.5 zip to install 0.5.5, but the RPM installation fails because it links to libpackagekitqt5.so.0.

This is expected, because it is compiled for SailfishOS 4.4.0, as the directory name inside the ZIP-archive shows.  Should be fine with the next release.

3. > STEPS TO REPRODUCE
   > Try to install SailfishOS:Chum GUI Installer on a device without Chum.

I will look at this issue; hope to find some time for it this weekend.

**Comment by ilpianista** [comment]
> I assume yesterday the target "4.5.0.18" was not configured for the
SailfishOS:Chum community repository at the SailfishOS-OBS; now it is, see at the bottom right of this page: https://build.merproject.org/project/show/sailfishos:chum
Thus the SailfishOS:Chum GUI Installer should be working fine now.

It does. I removed and installed the GUI installer again and it worked fine this time.

Thank you!

**Comment by Olf0** [comment]
Thank *you* for reporting and testing again!
