### ISSUE TITLE
[Help] Cannot setup Transifex integration

### ISSUE THREAD

**Issue by Olf0** [sailfishos-chum/sailfishos-chum-gui#160]
@rinigus, @piggz, I cannot setup the Transifex integration to make the strings translations much easier (making the dreaded `lupdate` & `lrelease` process optional instead of mandatory), because `This action must be performed by an organization owner`.  This is the last major action I intend(ed) to perform for SailfishOS:Chum (the GUI application, specifically).

The process is a bit complicated and tedious, specifically if one wants to grant Transifex (an Atlassian product!) minimal access privileges (read-only only for one specific repository).  I successfully set up this integration for Patchmanager 1,5 years ago, which requires multiple steps, both at GitHub and at Transifex.

As usual, please either perform this action on your own or grant me the rights to do it.  Actually I do suggest the latter, because I never understood why I was relegated to a second degree collaborator (it is extremely frustrating not to be able to perform simple maintenance tasks on one's own, as e.g. uploading a new organisation logo yesterday) and you might want to have a(nother) backup person around.  Ultimately I do not care too much (mostly for resolving the social imbalance and the recurring frustration, to have to beg again), because I plan to wind down my SFOS activities, as already stated.  The page for the most crucial step is https://github.com/apps/transifex-integration/installations , but IIRC it has to be triggered the right way (AFAIR from Transifex).

**Comment by rinigus** [comment]
I have made you an owner at the organization - re social balance. Sorry for earlier membership status. So, I presume you would be able to make those connections now.

**Comment by Olf0** [comment]
@piggz, @rinigus, as I do not want to establish myself as a potential single point of failure, I would like to make both of you co-admins at Transifex.com:
* @rinigus, is your personal account handle `rinigus - rinigus-github` at Transifex the right one to use?
* @piggz, do you have personal account at Transifex I might add as admin?

Basically I am all set with the Transifex integration; what remains do be done is the administrative work of inviting former i18n contributors at GitHub to Transifex and denoting in our documentation, that translations are preferably performed at Transifex.com.

P.S.: BTW, After having had a thorough look at the real life appearance of the organisation logo(s) with √2 transparent space around it for proper display with a circular cutting, I decided that here size does matter (for most views) and reverted the organisation logos for SailfishOS:Chum, SailfishOS-Patches and Storeman-Developers to the full size ones, despite the fact that they look strangely cut (only the centre part visible) at some places.  The same issue exists at Transifex.com, for now I uploaded the one with the √2 transparent spacing for SailfishOS:Chum GUI.

**Comment by rinigus** [comment]
Yes, my handle is "rinigus" at Transifex

**Comment by Olf0** [comment]
@piggz, you still may name your Transifex handle here, unless you do not want to be made a maintainer of [SailfishOS:Chum GUI](https://www.transifex.com/olf/sailfishos-chum-gui/dashboard/) there.

As I finished all other administrative and technical tasks related to establishing the Transifex integration for the SailfishOS:Chum GUI application, I am closing this issue.
