### ISSUE TITLE
Move this command out from translation

### ISSUE THREAD

**Issue by martonmiklos** [sailfishos-chum/sailfishos-chum-gui#173]
Hi folks,

I came across this string during translation:
https://github.com/sailfishos-chum/sailfishos-chum-gui/blob/5d0ce0aa0d7b1c80f88a216d367cd6676aa3c839/src/chum.cpp#L334

I would recommend to make the command untranslatable by adding a placeholder to it. 
For security reasons and to ease the translations.
What do you think?

**Comment by Olf0** [comment]
Yes, I also wondered once, if there is better way to handle this code line embedded in a text string.

> For security reasons and to ease the translations.

Can you please explain this a bit, specifically the security aspect.  I perceived it just as a small nuisance ("a bit ugly"), hence I did not mind to research and address this.

> I would recommend to make the command untranslatable by adding a placeholder to it.

I know there is a `notranslate` tag, but have no idea, if this is the right thing to use and how.

As always, PRs are welcome, then I might also understand better what solution you think of and how that looks like in practice.
<sub>Side note: I am merely little experienced with Qt's l10n infrastructure.</sub>

**Comment by Olf0** [comment]
> > Can you please explain this a bit, specifically the security aspect.
> 
> Well if one 'mis-translates' this string to end with an `rm -rf /` there could be an issue if someone copies it over and executes it.

Well, then this is about safety (not security), nevertheless the reasoning is valid. :+1:

**Comment by Olf0** [comment]
@martonmiklos, as your idea for rendering the shell code as immutable for translators is not ID-based, [your implementation suggestion](https://github.com/sailfishos-chum/sailfishos-chum-gui/issues/173#issuecomment-1477416087) has to be transformed to suite ID-based translatable Qt strings, first.

**Comment by Olf0** [comment]
Should be fixed by PR #215.

**Comment by Olf0** [comment]
PR #215 seems to work fine, but by looking at this text I realise to have never seen it before.  Thus I played bit with it and lastly created PR #253.

### Before
|   |   |
|---|---|
| ![Screenshot_20231110-1-v](https://github.com/sailfishos-chum/sailfishos-chum-gui/assets/16547876/357838e9-8f2b-4ced-bf82-020edd56bd9f) | ![Screenshot_20231110-2-v](https://github.com/sailfishos-chum/sailfishos-chum-gui/assets/16547876/1407a58d-3b76-414b-bc62-b502446ef69f) |

![Screenshot_20231110-2-h](https://github.com/sailfishos-chum/sailfishos-chum-gui/assets/16547876/1ddf7e84-634b-44dd-a36e-08b59c2927e5)
![Screenshot_20231110-1-h](https://github.com/sailfishos-chum/sailfishos-chum-gui/assets/16547876/7ed7414a-ca47-455e-a391-d5f21e10d2c9)

### After
