### ISSUE TITLE
[Bug] Can't disable repository version override

### ISSUE THREAD

**Issue by JacekJagosz** [sailfishos-chum/sailfishos-chum-gui#184]
**SailfishOS VERSION** (Settings → About product → Build): 4.5.0.19
<br />**HARDWARE** (Settings → About product → Manufacturer & Product name): Xperia 10 III
<br />**SailfishOS:Chum GUI application VERSION** (\<Top pulley\> → About): 0.5.7
<br />

#### BUG DESCRIPTION
When I first installed SFOS 4.5 I inputed repository override to 4.4.0.72, which worked great. Since then I updated the OS twice to 4.5.0.18 and then to .19. Each time the Chum GUI got removed and I had to reinstall it.
Even then it kept my user settings, and the override to 4.4. Many times I tried to remove that string, put different OS version there, remove the string and then enable testing repository, quit the app, try to synchronise... Each time I go back to settings the version string is back to 4.4.0.72.

#### STEPS TO REPRODUCE
Input repository version override, close the app, then open it again. From now on you can't remove it.

**Comment by rinigus** [comment]
I can confirm this bug

**Comment by rinigus** [comment]
I will look into it

**Comment by rinigus** [comment]
So, turned out that you just have to press Enter after clearing the version override. I have added it to the help text under the settings.

**Comment by JacekJagosz** [comment]
Ahhh, silly of my I didn't try that, thank you a lot for this awesome app!
