### ISSUE TITLE
[Bug] Web-links hardly readable, because they are rendered in dark blue

### ISSUE THREAD

**Issue by Olf0** [sailfishos-chum/sailfishos-chum-gui#186]
**SailfishOS:Chum GUI application VERSION** (\<Top pulley\> → About): All 0.5.x and 0.6.0
<br />

#### BUG DESCRIPTION
Most web-links are hardly readable when using a dark launcher background, because they are rendered in dark blue on most pages.  I observe this regularly on the [page for a specific issue](https://github.com/sailfishos-chum/sailfishos-chum-gui/blob/main/qml/pages/IssuePage.qml) and on the [page for a specific release](https://github.com/sailfishos-chum/sailfishos-chum-gui/blob/main/qml/pages/ReleasePage.qml).  I believe I also saw this on other pages (they rarely contain embedded web-links), ***but*** the ["About" page](https://github.com/sailfishos-chum/sailfishos-chum-gui/blame/main/qml/pages/AboutPage.qml) is fine; web-links there are rendered in turquoise, which is well visible on both dark and light backgrounds.

#### STEPS TO REPRODUCE
Look at pages for an individual issue or an individual release with embedded web-links, especially when the text of the links is long.  Compare this to the rendering of web-links on the "About" page.

#### Suggestion
Let all QML pages render web-links in the turquoise colour they have on the "About" page.

**Comment by Olf0** [comment]
## Screenshots depicting this issue
- **Bad**, displaying this issue
  ![Screenshot_20230403_001](https://user-images.githubusercontent.com/16547876/229635680-6e8436d0-2ec4-494f-baab-bf22279614e8.png)
- **Good**, showing the "About" page
  ![Screenshot_20230403_002](https://user-images.githubusercontent.com/16547876/229635751-a624435c-01fd-4cc1-9a1d-dd161e372d04.png)
- Even **worse** when a small font is used
  ![Screenshot_20230403_003](https://user-images.githubusercontent.com/16547876/229636009-f0153b59-d0fd-4c90-b284-293f14e0f05a.png)

**Comment by Olf0** [comment]
Unfortunately above mentioned commit (as part of PRs #200, #201 and #202) did not resolve this issue.

**Comment by rinigus** [comment]
If it works, it is fine by me :)

**Comment by Olf0** [comment]
Excellent, thank you @nephros!
