### ISSUE TITLE
[Enhancement] Optionally allow SFOS:Chum GUI app to ignore vendor changes when updating packages

### ISSUE THREAD

**Issue by Olf0** [sailfishos-chum/sailfishos-chum-gui#198]
@nephros discovered that [`packagekitd` ignores a vendor change if the method `install` is called for updating packages](https://github.com/storeman-developers/harbour-storeman/issues/406#issuecomment-1508312841) (instead of the method `update`).  See [that aforelinked thread](https://github.com/storeman-developers/harbour-storeman/issues/406#issuecomment-1508312841) for rationale and details.

This could be easily done for a single-package update by changing `update` to `install` in [line 398 of `src/chum.cpp`](https://github.com/sailfishos-chum/sailfishos-chum-gui/blob/main/src/chum.cpp#L398), but I do not know if this is the best way to implement this change and how to adapt that for [`updateAllPackages`](https://github.com/sailfishos-chum/sailfishos-chum-gui/blob/main/src/chum.cpp#L401-L414).
Furthermore the whole scheme of ignoring vendor changes when updating packages should be opt-in only, so it requires a switch in the settings.

I would appreciate much, if @rinigus and / or @piggz retraces the rationale and replies here, if this consideration is sound in your opinion.
Implementing this change should be a minor task for any experienced C++ programmer, when we reached consensus that this change constitutes an enhancement.

**Comment by rinigus** [comment]
Vendor was added to allow users to choose whether they use Chum or some other repository for particular package. 

Let's say you prefer Chum for package A that is also available in Jolla Store and OpenRepos. Without vendor, you would be on mercy of version-release differences between streams. For example, Jolla Store could have the same version but with larger release. 

Same goes for opposite - I may prefer OpenRepos for some package to Chum. 

So, vendor allows to pin the source of the package - as it is expected. While it causes issues for those who want to jump from one source to another, it prevents the issues that we will get by changing the source of the package automatically.

I consider it a feature and the needed one.

**Comment by Olf0** [comment]
> I consider it a feature and the needed one.

This is definitely the case for OpenRepos (and hence Storeman) as I [documented recently](https://github.com/storeman-developers/harbour-storeman/wiki/Storeman-&-vendor-changes#vendor-changes-of-packages-managed-by-storeman).

But the [assessment is different for the SailfishOS:Chum repository](https://github.com/storeman-developers/harbour-storeman/wiki/Storeman-&-vendor-changes#vendor-changes-of-packages-managed-by-the-sailfishoschum-gui-app), hence I wrote this suggestion above.

Actually there seems to be some misunderstandings in details:
- *"Without vendor, you would be on mercy of version-release differences between streams."*
  * This suggestion is not about eliminating vendor tag, which also is impossible for other "streams" (repositories), e.g. the Jolla Store.
  * Merely evaluating the version-release differences for a package in SailfishOS:Chum (compared to the same package in other repositories) might be wanted behaviour for some.
- *"For example, Jolla Store could have the same version but with larger release."*
  For this case the change suggested here would make no difference at all, because the SailfishOS:Chum GUI app does not access the Jolla Store rsp. its repository.
- *"So, vendor allows to pin the source of the package - as it is expected."*
  Though the first half of this statement is absolutely true, it is not what some people expect: They want the newest version, wherever it comes from.
- *"While it causes issues for those who want to jump from one source to another, it prevents the issues that we will get by changing the source of the package automatically."*
  Which issues do you mean to address here?  This is exactly the reason why my assessment for SailfishOS:Chum is different than for OpenRepos:
  * ["System package"-superseding packages are not allowed](https://github.com/sailfishos-chum/main#developers-guide) in SailfishOS:Chum.  Such packages are then principal reason why ignoring the vendor tag when updating with packages from OpenRepos is a "pretty bad idea"™.
  * All packages in SailfishOS:Chum are built in a fully traceable manner from their source, vastly reducing the risk of malicious software.
  * All packages in SailfishOS:Chum undergo manual approval twice: The first time fundamentally, weh a package is accepted into SailfishOS:Chum:Testing, and the each time when a package is submitted to SailfishOS:Chum proper.
- *"I consider it a feature and the needed one."*
  It definitely is a feature, but not a required one: Before the introduction of "[vendor stickiness](https://en.opensuse.org/SDB:Vendor_change_update)" about a decade ago, Linux distributions worked well without it.

After some pondering, I do concur that ignoring the vendor tag when the SailfishOS:Chum GUI app updates packages (implicitly only with ones in the SailfishOS:Chum repository) should be optional, because the current behaviour is well established and desirable for many.

**Comment by piggz** [comment]
I would back the view that the use of vendor stickiness is useful, and designed to cause less issues when updating.  If it was made optional, perhaps there should be a dialog/info of packages that would change vendor?  It may also be the case that users dont appreciate the concept of a vendor change, so perhaps a description or link out to some docs would be useful?

**Comment by rinigus** [comment]
> > For example, Jolla Store could have the same version but with larger release.

> For this case the change suggested here would make no difference at all, because the SailfishOS:Chum GUI app does not access the Jolla Store rsp. its repository.

Let me explain then on example: you can have Pure Maps from Chum and Jolla Store. They would have the same version but different release. Let's say Chum one has 3.2.0-1.jolla.1234 and Store has 3.2.0-2. In the store, release was set to 2 for one or another reason. When users will update some package at Chum (not necessarily Pure Maps, but anything else), `pkcon` in its great wisdom will update all packages it can (we had discussion regarding it already). And, if without vendor tag, Pure Maps will be "updated" to Jolla Store version.

That's a situation, vendor is designed to protect against and it is used by us accordingly. 

> They want the newest version, wherever it comes from. 

No, not really. Pure Maps in Jolla Store is significantly degraded when compared to Chum version. If user has selected a channel, that user should expect that the software updates would come from that channel as well.

Then again, there could be software that is distributed via Jolla Store and preferred by the user. Through vendor tag, we give a choice to the user and respect it.

I hope that my examples illustrated usefulness of vendor tag.

**Comment by Olf0** [comment]
> I hope that my examples illustrated usefulness of vendor tag.

Yes, they do.  I missed to take issue #67 (originally reported as [Storeman issue \#96](https://github.com/storeman-developers/harbour-storeman/issues/96) into account.

Sorry to have bothered you, sometimes I loose oversight of what I know.

⇒ Closing.
