### ISSUE TITLE
Handle Chum repo adding/removing from GUI

### ISSUE THREAD

**Issue by rinigus** [sailfishos-chum/sailfishos-chum-gui#21]
As developers may want to swap between chum:testing and chum as well as to simplify use, let's add Chum repo management to GUI. This seems to be possible via SSU DBus API. Both, testing and regular repo should be supported, probably one in a time.

It would allow users to install Chum GUI, add repo from it and just use that. Maybe, haven't looked into official Store requirements, we can even submit GUI there.

Note that we would have to remove requirement for chum package from RPM SPEC then.

**Comment by piggz** [comment]
Good idea
