### ISSUE TITLE
`sailfishos:chum` repository lacks `4.6`

### ISSUE THREAD

**Issue by Olf0** [sailfishos-chum/sailfishos-chum-gui#287]
@rinigus / @piggz, the `sailfishos:chum` and `sailfishos:chum:testing` repositories at Sailfish-OBS lack the [final release number for SailfishOS 4.5.0](https://forum.sailfishos.org/t/18127?u=olf#version-history-of-the-os-release-2) **`4.5.0.25`** (and  `sailfishos:chum` lacks `4.6`).  That means:
1. In the "meta" configuration of [`sailfishos:chum:testing`](https://build.sailfishos.org/project/meta/sailfishos:chum:testing) the entries for `4.5.0.24` shall be **overwritten** with:
   ```
     <repository name="4.5.0.25_i486">
       <path project="sailfishos:4.5.0.18" repository="latest_i486"/>
       <arch>i586</arch>
     </repository>
     <repository name="4.5.0.25_armv7hl">
       <path project="sailfishos:4.5.0.18" repository="latest_armv7hl"/>
       <path project="nemo:testing:hw:common" repository="sailfishos_4.5.0.25_armv7hl"/>
       <arch>armv8el</arch>
     </repository>
     <repository name="4.5.0.25_aarch64">
       <path project="sailfishos:4.5.0.18" repository="latest_aarch64"/>
       <path project="nemo:testing:hw:common" repository="sailfishos_4.5.0.25_aarch64"/>
       <arch>aarch64</arch>
     </repository>
   ```
2. In the "meta" configuration of [`sailfishos:chum`](https://build.sailfishos.org/project/meta/sailfishos:chum) the entries for `4.5.0.25` and `4.6` shall be **added** atop those for `4.5.0.24`:
   ```
     <repository name="4.6_i486">
       <path project="sailfishos:4.6" repository="latest_i486"/>
       <arch>i586</arch>
     </repository>
     <repository name="4.6_armv7hl">
       <path project="sailfishos:4.6:hw-common" repository="latest_armv7hl"/>
       <path project="sailfishos:4.6" repository="latest_armv7hl"/>
       <arch>armv8el</arch>
     </repository>
     <repository name="4.6_aarch64">
       <path project="sailfishos:4.6:hw-common" repository="latest_aarch64"/>
       <path project="sailfishos:4.6" repository="latest_aarch64"/>
       <arch>aarch64</arch>
     </repository>
     <repository name="4.5.0.24_i486">
       <path project="sailfishos:4.5.0.18" repository="latest_i486"/>
       <arch>i586</arch>
     </repository>
     <repository name="4.5.0.25_armv7hl">
       <path project="sailfishos:4.5.0.18" repository="latest_armv7hl"/>
       <path project="nemo:testing:hw:common" repository="sailfishos_4.5.0.25_armv7hl"/>
       <arch>armv8el</arch>
     </repository>
     <repository name="4.5.0.25_aarch64">
       <path project="sailfishos:4.5.0.18" repository="latest_aarch64"/>
       <path project="nemo:testing:hw:common" repository="sailfishos_4.5.0.25_aarch64"/>
       <arch>aarch64</arch>
     </repository>
   ```

Thank you!

**Comment by piggz** [comment]
Keto from Jolla created a symlink for the download repository to save space.  This means that although the projects doesnt display in OBS, the actual downloads continue to work.

**Comment by Olf0** [comment]
> Keto from Jolla created a symlink for the download repository to save space.

How is this symlink traceable / checkable?  I.e. from where to where does it exactly point?

> This means that although the projects doesnt display in OBS, the actual downloads continue to work.

Mmmh, what does this quite generic statement address specifically: Only `4.5.0.25`, or also `4.6` for `sailfishos:chum`?

**Comment by piggz** [comment]
Visit the repo url fro 4.5.0.24 eg https://repo.sailfishos.org/obs/sailfishos:/chum/4.5.0.25_aarch64/
Change 24 to 25, see the timestamps are the same.

**Comment by Olf0** [comment]
> Visit the repo url fro 4.5.0.24 eg https://repo.sailfishos.org/obs/sailfishos:/chum/4.5.0.25_aarch64/ Change 24 to 25, 

Thank you, now I see:
1. For `sailfishos:chum`
   * https://repo.sailfishos.org/obs/sailfishos:/chum/4.5.0.25_aarch64/
     equals
     https://repo.sailfishos.org/obs/sailfishos:/chum/4.5.0.24_aarch64/
   * https://repo.sailfishos.org/obs/sailfishos:/chum/4.5.0.25_armv7hl/
     equals
     https://repo.sailfishos.org/obs/sailfishos:/chum/4.5.0.24_armv7hl/
   * https://repo.sailfishos.org/obs/sailfishos:/chum/4.5.0.25_i486/
     equals
     https://repo.sailfishos.org/obs/sailfishos:/chum/4.5.0.24_i486/
2. For `sailfishos:chum:testing`
   * https://repo.sailfishos.org/obs/sailfishos:/chum:/testing/4.5.0.25_aarch64/
     equals
     https://repo.sailfishos.org/obs/sailfishos:/chum:/testing/4.5.0.24_aarch64/
   * https://repo.sailfishos.org/obs/sailfishos:/chum:/testing/4.5.0.25_armv7hl/
     equals
     https://repo.sailfishos.org/obs/sailfishos:/chum:/testing/4.5.0.24_armv7hl/
   * https://repo.sailfishos.org/obs/sailfishos:/chum:/testing/4.5.0.25_i486/
     equals
     https://repo.sailfishos.org/obs/sailfishos:/chum:/testing/4.5.0.24_i486/

> see the timestamps are the same.

Or better: Descend into `repodata` and see that the hashes are the same.

-------------------------------------------

Unfortunately, this is nothing I can utilise for Storeman, but as this is a single package, the waste of space is much less significant.  And with `4.6`, I will switch to a single repo for all SailfishOS 4.6.0.x releases, too.

--------------------------------------------

What remains of this issue are the missing `4.6` entries for `sailfishos:chum` proper.

**Comment by rinigus** [comment]
One more aspect: in addition to saving space, it avoids rebuilding Chum/ChumTesting for minor version changes. This rebuilds could easily take days in the current setup. Hopefully, this approach will work well in practice and get a leaner OBS as a result.

**Comment by piggz** [comment]
RE 4.6 ... we're still trying to get all of testing to build.  Quite a lot of packages are held up by changes to the opt-qt5/kf5 stuff which is having an issue.  Im away on holiday for a week, hopefully @rinigus will figure it out :)

**Comment by Olf0** [comment]
BTW, [`sailfishoschum-gui-installer`](https://openrepos.net/content/olf/sailfishoschum-gui-installer) should be able to handle the new naming scheme `<major>.<minor>_<arch>` as deployed in `sailfishos:chum:testing` for SailfishOS ≥ 4.6.

**Comment by Olf0** [comment]
> [What seems to remain of this issue](https://github.com/sailfishos-chum/sailfishos-chum-gui/issues/287#issuecomment-2132510844) are the missing `4.6` entries for `sailfishos:chum` proper:

This seems to be fine now, hence closing this issue.
