### ISSUE TITLE
[Bug] Chum GUI won't launch and won't refresh repository

### ISSUE THREAD

**Issue by E-Pa1N** [sailfishos-chum/sailfishos-chum-gui#296]
**SailfishOS VERSION** (Settings → About product → Build): 4.6.0.13
<br />**HARDWARE** (Settings → About product → Manufacturer & Product name): Sony Xperia 10 III
<br />**SailfishOS:Chum GUI application VERSION** (\<Top pulley\> → About): 0.6.8
<br />

#### BUG DESCRIPTION
Installation via RPM succeeds, icon appears in drawer.
Launching via icon results in loading screen, but stops and closes after several seconds have passed.
Launching via CLI results in missing library messages, two times a "Failed to obtain authentication" message, but strangely does launch the application with a "Failed to refresh SailfishOS:Chum repository" message

#### STEPS TO REPRODUCE
I'm starting to be quite sure this is something with my installation, but hopefully it can be resolved without a reinstall, plus I'm curious to figure out what exactly goes wrong!
But these are the steps:

Install RPM and launch from icon or CLI

#### ADDITIONAL INFORMATION
This is the relevant CLI output:

as devel-su: # pkcon install-local sailfishos-chum-gui-installer-0.6.5-1.noarch.rpm
Installing files
Testing changes
Finished
Testing changes
Installing files
Starting
Installing packages
Finished
Downloaded      sailfishos-chum-gui-installer-0.6.5-1.noarch (PK_TMP_DIR)
Installs SailfishOS:Chum GUI application
Installed       sailfishos-chum-gui-installer-0.6.5-1.noarch (PK_TMP_DIR)
Installs SailfishOS:Chum GUI application

$ sailfishos-chum-gui
[D] unknown:0 - Using Wayland-EGL
library "libui_compat_layer.so" not found
library "libutils.so" not found
library "libcutils.so" not found
library "libhardware.so" not found
library "android.hardware.graphics.mapper@2.0.so" not found
library "android.hardware.graphics.mapper@2.1.so" not found
library "android.hardware.graphics.mapper@3.0.so" not found
library "android.hardware.graphics.mapper@4.0.so" not found
library "libc++.so" not found
library "libhidlbase.so" not found
library "libgralloctypes.so" not found
library "android.hardware.graphics.common@1.2.so" not found
library "libion.so" not found
library "libz.so" not found
library "libhidlmemory.so" not found
library "android.hidl.memory@1.0.so" not found
library "vendor.qti.qspmhal@1.0.so" not found
[W] unknown:0 - Failed to refresh Chum repository "Failed to obtain authentication."
[W] unknown:0 - Failed to refresh Chum repository "Failed to obtain authentication."

Hopefully this works, but this should be the installer log:
[sailfishos-chum-gui-installer.log.txt](https://github.com/user-attachments/files/15887549/sailfishos-chum-gui-installer.log.txt)

**Comment by Olf0** [comment]
Thank you very much @E-Pa1N for your concise bug report.

Two quick replies from me
* You wrote
  > Launching via CLI […] strangely does launch the application …
  
  Does the SailfishOS:Chum GUI application actually work then?  If you want to be careful when testing this aspect, do not trigger operations which install or remove RPM packages.
* With regard to the `"Failed to obtain authentication."` messages, please see https://github.com/sailfishos-chum/sailfishos-chum-gui/issues/289#issuecomment-2167552946
* Installer log is absolutely O.K., everything went fine.
* As I did not (and do not) write the code of the SailfishOS:Chum GUI application, I have no idea, what causes the messages WRT multiple missing libraries.  But I can assure you, if libraries as e.g. `libutils`, `libcutils` and `libc++` were not installed, many other apps would / should not work properly.

Any ideas or comments from @rinigus and/or @piggz?

**Comment by E-Pa1N** [comment]
You're more than welcome 😊

![Screenshot_20240618_214208_001](https://github.com/sailfishos-chum/sailfishos-chum-gui/assets/165724449/317d9289-1cea-4ab1-af4b-169d3748d499)
![Screenshot_20240618_214159_001](https://github.com/sailfishos-chum/sailfishos-chum-gui/assets/165724449/41b44a97-cad1-44f6-b980-c9568167c91d)

**Comment by piggz** [comment]
Can you show the output of
ssu lr
thanks

**Comment by E-Pa1N** [comment]
$ ssu lr
WARNING: ssu.ini does not seem to be writable. Setting values might not work.
Enabled repositories (global): 
 - adaptation-common ... https://releases.jolla.com/releases/4.6.0.13/jolla-hw/adaptation-common/aarch64/
 - adaptation0       ... https://store-repository.jolla.com/releases/4.6.0.13/jolla-hw/adaptation-qualcomm-sony-lena/aarch64/
 - aliendalvik       ... https://store-repository.jolla.com/features/4.6.0.13/appsupport/aarch64/
 - apps              ... https://releases.jolla.com/jolla-apps/4.6.0.13/aarch64/
 - customer-jolla    ... https://releases.jolla.com/features/4.6.0.13/customers/jolla/aarch64/
 - hotfixes          ... https://releases.jolla.com/releases/4.6.0.13/hotfixes/aarch64/
 - jolla             ... https://releases.jolla.com/releases/4.6.0.13/jolla/aarch64/
 - sailfish-eas      ... https://store-repository.jolla.com/features/4.6.0.13/sailfish-eas/aarch64/
 - xt9               ... https://store-repository.jolla.com/features/4.6.0.13/xt9/aarch64/

Enabled repositories (user): 
 - harbour-storeman-obs      ... https://repo.sailfishos.org/obs/home:/olf:/harbour-storeman/4.6.0.13_aarch64/
 - openrepos-Mister_Magister ... https://sailfish.openrepos.net/Mister_Magister/personal/main
 - openrepos-Patchmanager    ... https://sailfish.openrepos.net/Patchmanager/personal/main
 - openrepos-Polleke         ... https://sailfish.openrepos.net/Polleke/personal/main
 - openrepos-ade             ... https://sailfish.openrepos.net/ade/personal/main
 - openrepos-ichthyosaurus   ... https://sailfish.openrepos.net/ichthyosaurus/personal/main
 - openrepos-olf             ... https://sailfish.openrepos.net/olf/personal/main
 - openrepos-rinigus         ... https://sailfish.openrepos.net/rinigus/personal/main
 - openrepos-rubdos          ... https://sailfish.openrepos.net/rubdos/personal/main
 - openrepos-vasvlad         ... https://sailfish.openrepos.net/vasvlad/personal/main
 - sailfishos-chum           ... https://repo.sailfishos.org/obs/sailfishos:/chum/4.6_aarch64/
 - store                     ... https://store-repository.jolla.com/xqbt52/aarch64/?version=4.6.0.13

**Comment by piggz** [comment]
Ok, so the repo looks to be created fine.....

Can you do the following:
ssh into the device and gain root
capture the output of:
journalctl -f

While on the phone, opening the app

Paste in some pastebin service.

**Comment by E-Pa1N** [comment]
[chumcapture.txt](https://github.com/user-attachments/files/15892047/chumcapture.txt)

In this capture I've both opened the app via GUI (first attempt) and then CLI (second attempt)

**Comment by E-Pa1N** [comment]
Some extra information:

- Having manually run pkcon refresh and zypper refresh (I don't know if those do the same thing?) I could now update the application "Mimic" successfully, and browse Installed and available packages properly.
- Starting Chum GUI via the icon still fails
- Starting via CLI succeeds and throws a couple of additional content-related errors (can't find .svg files and certain URLs)
- Refreshing the repository via Chum GUI still fails

**Comment by E-Pa1N** [comment]
All open issues I had have been solved since yesterday, don't exactly know what fixed it (perhaps an update pushed via a repo?) but Chum GUI is working well, opening via the launcher icon, refreshing repositories, and I can update and install applications just fine!

**Comment by Olf0** [comment]
Some extra feedback:
> * Starting via CLI succeeds and throws a couple of additional content-related errors (can't find .svg files and certain URLs)

These are usually caused by dead (i.e. no link target exists any longer) or broken (i.e. typos etc.) web-links in the SailfishOS:Chum metadata of some packages.  If you take a closer look at the links named as cause in these error messages, you will easily determine which package metadata is causing each of them.  If you want to be kind, look up the SailfishOS:Chum metadata in the `rpm/<package-name>.spec` file of an affected packages at GitHub (or wherever the package source code is hosted at), try to determine what is wrong (see above: broken or dead link?) and write a bug report for that package.  If you know exactly what is wrong and how to fix it (e.g. a typo), you can also submit a PR (pull request) fixing the issue instead of the bug report: At GitHub's / GitLab's / Codeberg's web-UI this can be accomplished quite easily.
