### ISSUE TITLE
Finalize the first release and bring it to sailfishos:chum

### ISSUE THREAD

**Issue by rinigus** [sailfishos-chum/sailfishos-chum-gui#3]
Right now we have GUI in :testing sub-repository. To promote it to sailfishos:chum, we need

- decide which SFOS versions are supported. Currently, builds for newest releases are OK only in https://build.sailfishos.org/package/show/sailfishos:chum:testing/sailfishos-chum-gui

- tag the release and update _service at OBS with it.

Note that OBS would prefer releases in the form `X.Y.Z` - without any dash. Dash and Release number is added by OBS internally to distinguish the builds. So, we better use corresponding format for releases as well. I would suggest 0.2.0 as the next one (no `v` in front).

**Comment by mentaljam** [comment]
I want to implement more basic functions and then tweak the code for OBS.

**Comment by mentaljam** [comment]
Done!
