### ISSUE TITLE
About page missing

### ISSUE THREAD

**Issue by rinigus** [sailfishos-chum/sailfishos-chum-gui#30]

**Comment by piggz** [comment]
What info should we provide in the about page?

**Comment by rinigus** [comment]
I guess we need regular app info (icon, version, license, its repo issue link) but also some recap from https://github.com/sailfishos-chum/main . Its probably a good location to give a short intro into Chum repos. In addition, we should link to https://github.com/sailfishos-chum/main/issues as a location for reporting bugs, requests
