### ISSUE TITLE
Change order of "Update" and "Uninstall" in pulley menu

### ISSUE THREAD

**Issue by peperjohnny** [sailfishos-chum/sailfishos-chum-gui#71]
Currently if you have an installed app which has an update available, your options from the pulley are "Uninstall" and above that "Update". My guess is that people would want to update more often than uninstall and therefore to switch up the entries in the pulley. Anecdotally I wanted to update the chum-gui app recently and instead of updating, I uninstalled it. Also it would be consistent with other store apps, like the jolla store and storeman.

**Comment by rinigus** [comment]
Good point, we will change the order
