### ISSUE TITLE
[Suggestion] Reorder pulley menu entries for a package

### ISSUE THREAD

**Issue by Olf0** [sailfishos-chum/sailfishos-chum-gui#79]
*Uninstall* should be the top-most entry (not the bottom-most, as it currently is), in order to avoid triggering a package removal accidentally.
If that causes the *Install* entry (as the counterpart of the *Uninstall* one) to be at the top too, that is O.K. IMO.

The order of the other pulley menu entries is fine.

**Comment by rinigus** [comment]
I was pondering it when made the last change. You are right, let's push Uninstall all up. Install can stay as the first one.
