### ISSUE TITLE
Drop description in TextField

### ISSUE THREAD

**Issue by rinigus** [sailfishos-chum/sailfishos-chum-gui#81]
As older SFOS versions don't seem to have it, drop that field in Settings.

**Comment by Olf0** [comment]
This is working fine: The Settings page of SailfishOS:Chums-GUI 0.4.0-1 opens on SFOS 3.2.1.

For background info [see piggz comment](https://github.com/sailfishos-chum/sailfishos-chum-gui/pull/87#issuecomment-1013658705):
> I took a look on wayback machine, and yes, description must have been added after sep 2020 https://web.archive.org/web/20200925155838/https://sailfishos.org/develop/docs/silica/qml-sailfishsilica-sailfish-silica-textfield.html/
