### ISSUE TITLE
Replace invoker call for older SFOS versions

### ISSUE THREAD

**Issue by rinigus** [sailfishos-chum/sailfishos-chum-gui#82]
Related to issue #7: Use `invoker --type=generic` for SFOS 3.2 and maybe few other older ones.

**Comment by rinigus** [comment]
@olf: if you replace in .desktop 

```
X-Nemo-Application-Type=silica-qt5
```

With 
```
X-Nemo-Application-Type=generic
```

then GUI will start from the launcher, right?

**Comment by rinigus** [comment]
Had a wrong ping earlier. @Olf0, could you check whether such change would fix your issue?

**Comment by Olf0** [comment]
1. Mmmh, a path would have been helpful.  Found: /usr/share/applications/sailfishos-chum-gui.desktop
2. Cannot edit it with `vi`!?!  `vi /usr/share/applications/sailfishos-chum-gui.desktop` (as root) opens an empty file!
    Do you understand why?
3. `sed -i 's/silica-qt5/generic/' sailfishos-chum-gui.desktop` seems to have done the job.
4. Yes, it works as expected.

**Comment by rinigus** [comment]
Thanks! No idea why you cannot edit it with vi as root. I was able to open it as expected
