### ISSUE TITLE
Easing installation

### ISSUE THREAD

**Issue by Olf0** [sailfishos-chum/sailfishos-chum-gui#96]
The current installation process of the SailfishOS:Chum GUI app is very tedious: An RPM has to be selected (by manually inputting installed SailfishOS release version and used CPU architecture as parameters), then downloaded and installed in a manual process, either guided at [ChumRPM.netlify.app](https://chumrpm.netlify.app/) or fully manually at [SailfishOS:Chum/sailfishos-chum-gui](https://build.sailfishos.org/package/show/sailfishos:chum/sailfishos-chum-gui).

One idea in order to automate the installation was to try deploying a timer unit from a generic RPM, which downloads and installs the appropriate SailfishOS:Chum-GUI RPM (see as reference https://github.com/mentaljam/harbour-storeman-installer/issues/2#issuecomment-956020383), and may ultimately delete itself or trigger "uninstalling" (removing) the RPM which deployed it, which in turn will remove the timer unit proper.

**Comment by Olf0** [comment]
Actually this has become less urgent for the SailfishOS:Chum GUI client app than for Storeman, because recent commits (e.g., #82) allow the GUI client app to run on any SailfishOS release since (at least) v3.2.1.
And libzypp rsp. libsolv successfully manages to handle the same RPM for different architectures in a single repository, while it started to fail managing multiple variants of the same basic RPM with different, mutually exclusive dependencies in a single repository a few years ago.

Hence I uploaded the [SailfishOS:Chum GUI client app at OpenRepos](https://openrepos.net/content/olf/sailfishoschum-gui-client-app) as suggested by [Rinigus](https://github.com/sailfishos-chum/main/issues/45#issuecomment-1030261921).

**Comment by rinigus** [comment]
Thank you very much for doing it!

**Comment by Olf0** [comment]
See what SSU does (using a `add-oneshot`): https://github.com/mentaljam/harbour-storeman-installer/issues/2#issuecomment-1056128599

This looks promising to me.

**Comment by Olf0** [comment]
Addressed by the creation of https://github.com/sailfishos-chum/sailfishos-chum-gui-installer
